---
name: CI libs/base

on:
  pull_request:
    paths:
      - 'dev-requirements.txt'
      - 'pip-requirements.txt'
      - '.github/workflows/python_reusable.yml'
      - '.github/workflows/ci_base.yml'
      - 'libs/base/**'
  workflow_dispatch:  # Allows to trigger the workflow manually in GitHub UI

jobs:
  ci-libs-base:
    uses:
      ./.github/workflows/python_reusable.yml
    with:
      working-directory: libs/base
    secrets: inherit
