---
name: Reusable job for Python CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"

jobs:
  python-lib-ci:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version: ${{ inputs.python-version }}

      - name: Install Python dependencies
        run: |
          pip install -r "$(git rev-parse --show-toplevel)/pip-requirements.txt"
          pip install -r "$(git rev-parse --show-toplevel)/dev-requirements.txt"

      - name: Typecheck
        run: |
          pyright .
