name: Continuous integration
on: push

jobs:
  deploy:
    # Allows the Sibz/github-status-action action to update the status.
    permissions:
      statuses: write
      id-token: write
      contents: read
      pull-requests: read

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "yarn"
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Deploy to Netlify
        id: deploy
        run: |
          [[ "$GITHUB_REF" == "refs/heads/master" ]] && flags=--prod
          # Awk is required because netlify outputs some warnings on stdout.
          npx netlify deploy $flags --json | awk "/{/,/}/" | tee result.json
          echo "::set-output name=deploy_url::$(jq -r .deploy_url result.json)"
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
      - name: Add commit status
        uses: Sibz/github-status-action@v1.1.6
        with:
          authToken: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.event.pull_request.head.sha || github.sha }}
          context: deploy/netlify
          description: Deploy preview ready
          state: success
          target_url: ${{ steps.deploy.outputs.deploy_url }}
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: yarn install --frozen-lockfile
      - run: yarn lint
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          check-modified-files-only: "yes"
