name: Percy diff
on:
  pull_request:
    types:
      - labeled
      - opened
      - synchronize
jobs:
  percy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: yarn install --frozen-lockfile
      - run: yarn build
      - name: Run percy
        run: |
          npx percy snapshot --config .percy.yml
        if: ${{ contains(github.event.pull_request.labels.*.name, 'percy') || github.ref == 'refs/heads/master' }}
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
