---
name: Reusable Python library CI

on:
  workflow_call:
    inputs:
      working-directory:
        required: true
        type: string
        description: "From which folder this pipeline executes"
      install-packages:
        description: "Space seperated list of packages to install using apt-get."
        default: ""
        type: string
      # To avoid being billed 360 minutes if a step does not terminate
      # (we've seen the setup-python step below do so!)
      ci-timeout:
        description: "The timeout of the ci job. Default is 25min"
        default: 25
        type: number

jobs:
  local-ci-py-template:
    runs-on: ubuntu-22.04
    timeout-minutes: 30

    defaults:
      run:
        working-directory: ${{ inputs.working-directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v4
        timeout-minutes: 5
        with:
          python-version-file: ${{ github.workspace }}/.python-version
          cache: "pip"
          cache-dependency-path: |
            dev-requirements.txt
            pip-requirements.txt
            ${{ inputs.working-directory }}/requirements.txt

      - name: Install extra packages
        if: ${{ inputs.install-packages != ''}}
        run: |
          sudo apt-get install -y ${{ inputs.install-packages }}

      - name: Install Python dependencies
        run: |
          pip install -r "$(git rev-parse --show-toplevel)/pip-requirements.txt"
          pip install -r "$(git rev-parse --show-toplevel)/dev-requirements.txt" -r requirements.txt

      - name: Typecheck
        run: |
          pyright .

      - name: Test
        run: |
          python3 -m pytest tests/  # Assume that tests are in folder "tests/"
