name: Continuous integration
on: [push]

jobs:
  build:
    name: Lint & Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          lfs: true
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run lint
      - run: npm run build
